# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - onlined-fe

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://onlined.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_69abd21bbc584867b4741f8fefddebfc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a1c15fe89ec54f75bb5b3373fa43fe87 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: onlined.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_69abd21bbc584867b4741f8fefddebfc }}/onlined-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'onlined-fe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1d6624b017a84c8da8505e66c8328380 }}
        images: 'onlined.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_69abd21bbc584867b4741f8fefddebfc }}/onlined-frontend:${{ github.sha }}'